Repository zurichat/zc_main, pull requests merged in 2021-09, with the labels that each got.

#625 Feat/zurichat section 6 read more
  .prettierignore
  zc_frontend/src/pages/zurichat-section-6/index.js
  zc_frontend/src/pages/zurichat-section-6/styles.css
Labels: team-aristotle

#657 Feat/section4 pricing page
  zc_frontend/public/Everlane-logo-color@2x 1.png
  zc_frontend/public/Logo@2x 1.png
  zc_frontend/public/Shopify-color-logo@2x 1.png
  zc_frontend/public/Slack-Customer-Shopify-hero@2x-1 1.png
  zc_frontend/public/airbnb-logo@2x 1.png
  zc_frontend/public/ameritrade-logo@2x.png
  zc_frontend/public/autodesk-logo@2x.png
  zc_frontend/public/customer-lyft-logo@2x 1.png
  zc_frontend/public/electronic-arts-logo@2x.png
  zc_frontend/public/intuit-quickbooks-hero@2x-1 1.png
  zc_frontend/public/lyft-slack-customer@2x 1.png
  zc_frontend/public/oracle-logo@2x.png
  zc_frontend/public/slack-customer-everlane-hero 1.png
  zc_frontend/public/target-logo@2x.png
  zc_frontend/src/pages/pricing/components/CardComponentPricingPage.js
  zc_frontend/src/pages/pricing/components/LogoComponent.js
  zc_frontend/src/pages/pricing/components/Section4_pricing_page.js
  zc_frontend/src/pages/pricing/index.js
  zc_frontend/src/pages/pricing/styles/CardComponentPricingPage.module.css
  zc_frontend/src/pages/pricing/styles/LogoComponent.module.css
  zc_frontend/src/pages/pricing/styles/Section4_pricing_page.module.css
Labels: accepted, team-aristotle

#688 Converted Header component design to code #491
  zc_frontend/src/components/externalPagesComponents/Header.js
  zc_frontend/src/styles/Header.module.css
Labels: team-aristotle

#689 Feat/zurichat section 6. Learn more about the zurichat
  zc_frontend/src/pages/features/components/Section6.js
  zc_frontend/src/pages/features/index.js
  zc_frontend/src/pages/features/styles/section6.module.css
  zc_frontend/src/pages/pricing/components/CardComponentPricingPage.js
  zc_frontend/src/pages/pricing/components/LogoComponent.js
  zc_frontend/src/pages/pricing/components/Section4_pricing_page.js
Labels: team-aristotle

#705 Feat/footer
  zc_frontend/public/facebook.svg
  zc_frontend/public/instagram.svg
  zc_frontend/public/linkedin.svg
  zc_frontend/public/rectangle.svg
  zc_frontend/public/twitter.svg
  zc_frontend/src/assets/mobileBackground.svg
  zc_frontend/src/assets/rectangle.svg
  zc_frontend/src/components/externalPagesComponents/Footer/Footer.js
  zc_frontend/src/components/externalPagesComponents/Footer/Footer.module.css
  zc_frontend/src/components/externalPagesComponents/Footer/Message.js
  zc_frontend/src/components/externalPagesComponents/Footer/Message.module.css
  zc_frontend/src/pages/careers/index.js
  zc_frontend/src/styles/Footer.module.css
Labels: team-aristotle

#641 Created a input component for the external pages
  package.json
  zc_frontend/src/components/externalPagesComponents/Input.js
Labels: team-aristotle

#663 Feat/pricing page section 1 design conversion
  zc_frontend/package.json
  zc_frontend/public/checkmark.svg
  zc_frontend/src/pages/pricing/pricingPageSection1/PricingDummyData.js
  zc_frontend/src/pages/pricing/pricingPageSection1/PricingPageSection1.css
  zc_frontend/src/pages/pricing/pricingPageSection1/PricingPageSection1.js
Labels: team-aristotle

#740 special features you didn't know you needed
  zc_frontend/src/pages/features/components/SpecialFeatures.js
  zc_frontend/src/pages/features/styles/SpecialFeatures.css
Labels: team-aristotle

#667 Feat/apps and integration(categories)
  zc_frontend/src/App.js
  zc_frontend/src/pages/apps-integrations/Categories.js
  zc_frontend/src/pages/apps-integrations/index.js
  zc_frontend/src/styles/Categories.module.css
Labels: team-aristotle

#804 Add Sign Up validation rules for frontend - Team Einstein - closes #281
  zc_frontend/public/index.html
  zc_frontend/src/components/LandingPage.js
  zc_frontend/src/pages/images/apple.svg
  zc_frontend/src/pages/images/bg.svg
  zc_frontend/src/pages/images/bgpng.png
  zc_frontend/src/pages/images/chevron.svg
  zc_frontend/src/pages/images/globe.svg
  zc_frontend/src/pages/images/google.svg
  zc_frontend/src/pages/images/zuri.svg
  zc_frontend/src/pages/signup/index.js
  zc_frontend/src/styles/Signup.module.css
  zc_frontend/yarn.lock
Labels: team-einstein, front-end

#911 password toggle fix && disable button if no input
  package.json
  yarn.lock
  zc_frontend/src/pages/login/index.js
  zc_frontend/src/pages/login/styles/Login.module.css
  zc_frontend/src/styles/Login.module.css
Labels: team-einstein, frontend
