Repository zurichat/zc_main, pull requests merged in 2022-11, with the labels that each got.

#2583 ZUR-117 move file attach button to the front of the chat box menu options
  packages/ui/src/message-pane-input/components/Toolbar.jsx
Labels: accepted

#2588 ZUR-106 My PR removes the filter that clears the content under the input box in the status model
  packages/main/src/components/protected/topbar/components/NewStatusModal.jsx
Labels: accepted

#2558 feat: changed the alert method when the 'get a shareable link' is clicked.
  packages/main/src/pages/protected/create-workspace/Step3.jsx
Labels: accepted

#2564 ZUR-95: improvement - Autofocus when the search bar is clicked
  packages/main/src/components/protected/topbar/components/TopBarSearchModal.jsx
Labels: accepted

#2556 ZUR-102 Updated the padding for the icon in the search bar in the status modal
  packages/main/src/components/protected/topbar/styles/SetStatusModal.module.css
Labels: accepted

#2559 Format toolbar
  packages/main/src-old/pages/UI/MsgBoard.js
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
  packages/ui/src/message-pane-input/components/Toolbar.jsx
Labels: Conflicts

#2541 ZUR-192 My pull request fixes translations issue on the download page
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/DownloadDesktop.js
  packages/main/src/translations/translation-dictionary/pages/DownloadIos.js
  packages/main/src/translations/translation-dictionary/pages/DownloadMac.js
  packages/main/src/translations/translation-dictionary/pages/DownloadMobile.js
  packages/main/src/translations/translation-dictionary/pages/DownloadWindows.js
Labels: accepted

#2540 ZCG_23 Fix: The drop menu is now well positioned
  packages/main/src/components/protected/topbar/styles/Topbar.module.css
Labels: accepted

#2542 ZUR-99:feat: Added the hover tooltip for the status
  packages/main/src/components/protected/topbar/components/TopNavbar.jsx
  packages/main/src/components/protected/topbar/styles/TopNavBar.module.css
Labels: accepted

#2605 ZUR-138 remove unnecessary icons from create workspace page
  packages/main/src/pages/protected/create-workspace/Step0.jsx
Labels: accepted

#2585 ZUR-108 : Feat/updatechannelgroupheader
  packages/main/src/components/protected/sidebar/styles/Drop.module.css
Labels: accepted

#2591 ZUR-164 Add the modal for the channels description
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
  packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
Labels: accepted

#2596 ZUR-194: fix- fixed translation language on the download page (section two)
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/DownloadDesktopSectionTwo.js
  packages/main/src/translations/translation-dictionary/pages/DownloadMobileSectionTwo.js
Labels: accepted

#2581 ZUR-193 : Fix the translation language on the button (download page)
  packages/main/src/pages/protected/create-workspace/Step0.jsx
  packages/main/src/pages/static/downloads/components/DownloadsDesktop.jsx
  packages/main/src/pages/static/downloads/components/DownloadsMobile.jsx
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/Download.js
Labels: accepted, Conflicts

#2584 ZUR-112 My PR changes the workspace dropdown items color when hovered.
  packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css
Labels: accepted

#2565 ZUR-129 My PR removes the unnecessary footer links in the Home Page
  packages/main/src/components/footer/Footer.jsx
  packages/main/src/translations/translation-dictionary/components/NavBar.js
Labels: accepted

#2546 [ZUR-154] Move Plugin link to the footer & Fix Plugin Page
  packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
  packages/main/src/pages/protected/workspace/Workspace.jsx
  packages/main/src/pages/static/plugins/index.css
  packages/main/src/pages/static/plugins/index.jsx
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
Labels: accepted, Conflicts

#2551 ZUR-101 My PR Reduce the gap in the profile dropdown
  packages/main/src/components/protected/topbar/styles/Topbar.module.css
Labels: accepted

#2576 ZUR-104 My PR patches distortions in the set status modal.
  packages/main/src/components/protected/topbar/styles/SetStatusModal.module.css
Labels: accepted

#2574 ZUR-151 My PR cleans up the legal page and added the loader component
  packages/main/src-old/pages/termsOfService/components/content.js
Labels: accepted

#2602 ZUR-135 My PR adds a feature "removed billings and pricing from contact Page"
  packages/main/src/pages/static/contact-us/faq/detailsArray.js
  packages/main/src/pages/static/contact-us/faq/en.js
  packages/main/src/pages/static/contact-us/faq/es.js
  packages/main/src/pages/static/contact-us/faq/fr.js
Labels: accepted

#2560 ZUR-121 fixed the contact us page in the login form
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx
Labels: accepted

#2578 ZUR-128: Redesign HomePage
  packages/main/src/pages/home/Home.jsx
  packages/main/src/pages/home/Home.module.css
Labels: accepted

#2610 Add the ability to add people via the channels modal - ZUR-168
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
  packages/ui/src/message-room-details-dialog/components/AddMemberModal.jsx
  packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
  packages/ui/src/utils/samples/sample-member-list.js
Labels: accepted

#2563 Fixing Workspace dropdown items (Adding spaces)
  packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css
Labels: accepted

#2548 ZUR-140 My PR centers the text on the left side of the icons in the create-workspace page
  packages/main/src/pages/protected/create-workspace/Step0.jsx
Labels: accepted

#2597 Contact link added to the bottom of the page #134
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx
Labels: accepted

#2601 ZUR-97 My PR Adds a filter modal for the global search
  packages/main/src/components/protected/topbar/components/TopBarSearchModal.jsx
  packages/main/src/components/protected/topbar/components/TopBarSearchModalUI.jsx
  packages/main/src/components/protected/topbar/styles/TopBarSearchModal.module.css
  packages/main/src/components/protected/topbar/styles/TopBarSearchModalUI.module.css
Labels: accepted

#2577 ZUR-190 Ft language dutch
  packages/main/src/components/protected/sidebar/components/Drop.jsx
  packages/main/src/components/protected/sidebar/components/RoomItem.jsx
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/sidebar/components/Starred.jsx
  packages/main/src/components/protected/topbar/components/TopBarSearchModal.jsx
  packages/main/src/translations/locales (not used)/de/translations.js
  packages/main/src/translations/locales (not used)/en/translations.js
  packages/main/src/translations/locales (not used)/fr/translations.js
  packages/main/src/translations/translation-dictionary/components/NavBar.js
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/WorkspaceChat.js
  packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
Labels: accepted

#2609 Integrate a gif platform (Giphy Platform)
  packages/ui/package.json
  packages/ui/src/message-pane-input/components/Gif.module.css
  packages/ui/src/message-pane-input/components/Toolbar.jsx
  yarn.lock
Labels: accepted

#2562 Fix: Fixed poor hover effect on the globe icon in the top navigation bar -ZUR-126
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
Labels: accepted

#2594 Create/complete the contact form in the contact page; ZUR-137
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.module.css
Labels: accepted

#2600 ZUR-139: Add a why zuri chat page
  packages/main/src/App.js
  packages/main/src/pages/WhyZuriChat/Whyzurichat.js
  packages/main/src/pages/WhyZuriChat/assets/MacBookAir.svg
  packages/main/src/pages/WhyZuriChat/assets/assets.zip
  packages/main/src/pages/WhyZuriChat/assets/undraw_Active_support_re_b7sj.svg
  packages/main/src/pages/WhyZuriChat/assets/undraw_Memory_storage_reh0.svg
  packages/main/src/pages/WhyZuriChat/assets/undraw_Messages_re_qy9x.svg
  packages/main/src/pages/WhyZuriChat/assets/undraw_Organize_resume_re_k45b.svg
  packages/main/src/pages/WhyZuriChat/assets/undraw_Site_stats_re_ejgy.svg
  packages/main/src/pages/WhyZuriChat/assets/undraw_Texting_re_l11n.svg
  packages/main/src/pages/WhyZuriChat/assets/undraw_good_team_m7uu.svg
  packages/main/src/pages/WhyZuriChat/styles/whyzurichat.module.css
  packages/main/src/pages/index.js
Labels: accepted

#2516 Fix/contactpage issueId = ZCG_12
  packages/main/src-old/components/Button.js
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx
  packages/main/src/pages/static/contact-us/components/ContactMain.module.css
Labels: accepted

#2617 [ZUR-114] feat: company icon should show up in the workspace dropdown
  packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
Labels: accepted

#2554 ZUR-142 My PR updates member count spacing for create-workspace list and aligns the workspace name and the right arrow
  packages/main/src/components/user-organisations-listing/UserOrganisationsListing.jsx
Labels: accepted

#2555 Login Page Font Mismatch Fix
  packages/main/src/pages/login/Login.module.css
  packages/main/src/styles/global.css
Labels: accepted

#2570 Fix: Sidebar Faster Loading ZUR-144
  packages/main/src/components/protected/sidebar/index.jsx
  packages/main/src/pages/protected/workspace/Workspace.jsx
Labels: accepted

#2590 Zur-125/ Fixed Top right items space
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
Labels: accepted

#2613 [ZUR-171] Fix Bottom Alignment of Message Panel and Page Scroll Issue
  packages/ui/src/message-board/MessageBoard.jsx
  packages/ui/src/message-board/MessageBoard.styled.js
  packages/ui/src/message-pane/message-pane.module.css
  yarn.lock
Labels: accepted

#2612 ZUR-184 feat: ability to react to messages and images in rooms
  packages/ui/src/message-board/MessageBoard.jsx
  packages/ui/src/message-pane/MessagePane.jsx
  packages/ui/src/message-pane/message-pane.module.css
Labels: accepted

#2573 Feat/deactivate send chat button when chatbox is empty
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
  packages/ui/src/message-pane-input/components/Toolbar.jsx
  packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
Labels: accepted, Conflicts

#2603 ZUR-152 My PR removes all import leading to the src-old folder and also all unused refs #2603
  packages/main/src/components/link/Link.js
  packages/main/src/components/link/Link.module.css
  packages/main/src/pages/static/privacy-policy/assets/padlock.png
  packages/main/src/pages/static/privacy-policy/components/Content.js
  packages/main/src/pages/static/privacy-policy/styles/content.module.css
Labels: accepted

#2626 ZUR 143 vertical alignment of the text on the workspace (chat name and member count)
  packages/main/src/components/user-organisations-listing/UserOrganisationsListing.jsx
Labels: accepted

#2611 ZUR-115 My PR fixes a bug
  packages/ui/src/message-pane-input/EmojiStyles.styled.js
Labels: accepted

#2629 Fixes linear-ticket ID ZUR-92 to fix the translation rendering issues.
  packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
  packages/main/src/components/protected/topbar/components/TopbarModal.jsx
  packages/main/src/components/user-organisations-listing/UserOrganisationsListing.jsx
  packages/main/src/pages/home/Home.jsx
  packages/main/src/pages/protected/choose-workspace/ChooseWorkspace.jsx
  packages/main/src/translations/translation-dictionary/components/ModalComponent.js
  packages/main/src/translations/translation-dictionary/components/TopBarModal.js
  packages/main/src/translations/translation-dictionary/components/UserOrganizationsListing.js
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/Home.js
  packages/main/src/translations/translation-dictionary/pages/Workspace.js
  packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
Labels: accepted

#2631 Chore: Remove Zurichat blog
  packages/main/src-old/pages/blogs/components/zurichatBlog.js
  packages/main/src-old/pages/blogs/components/zurichatBlog.module.css
Labels: accepted

#2635 ZUR 132: Remove the downloads page and links to it
  packages/main/src/App.js
  packages/main/src/components/footer/Footer.jsx
  packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
  packages/main/src/components/protected/topbar/components/TopbarModal.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
Labels: accepted

#2627 Ability to add previously send file Features Implemented
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
  packages/ui/src/message-room-details-dialog/components/File.jsx
  packages/ui/src/message-room-details-dialog/components/FileList.jsx
  packages/ui/src/message-room-details-dialog/components/FileShowMoreModal.jsx
  packages/ui/src/message-room-details-dialog/fileData.js
Labels: accepted

#2640 [ZUR-171 - Continued] PR fixes the issue of the message input box's misalignment with the message board,
  packages/ui/src/message-board/MessageBoard.styled.js
  packages/ui/src/message-pane/message-pane.module.css
Labels: accepted

#2639 ZUR - 115 My PR fixes a bug where the chat box alignment is fixed
  packages/ui/src/message-pane-input/EmojiStyles.styled.js
Labels: accepted

#2638 ZUR-136 Change text and border radius of sidebar on active
  packages/main/src/components/protected/sidebar/assets/icons/hash.svg
  packages/main/src/components/protected/sidebar/assets/icons/hash2.svg
  packages/main/src/components/protected/sidebar/components/RoomItem.jsx
  packages/main/src/components/protected/sidebar/styles/Drop.module.css
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/pages/static/contact-us/index.jsx
Labels: accepted

#2642 Fix: Addressed the z-index issue with the channels description modal.
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
Labels: accepted

#2636 ZUR-110 fix positioning and alignment in dropdown when you click workspace …
  packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css
Labels: accepted

#2595 Feat/sidebar hashtag
  packages/main/src/components/protected/sidebar/styles/Drop.module.css
Labels: accepted

#2645 Fixed issue My PR fixes ID-141
  packages/main/src/components/protected/sidebar/components/Drop.jsx
  packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
  packages/main/src/components/user-organisations-listing/UserOrganisationsListing.jsx
Labels: accepted

#2637 Set status modal
  packages/main/src/components/protected/topbar/components/SetStatusModal.jsx
Labels: accepted

#2499 Style/toolbar Fix style issues on the chatbox - ID ZCG_24
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
Labels: accepted

#2648 #ZUR-173 feat: created a shortcuts modal UI for shortcuts icon on the message input box.
  packages/ui/src/message-pane-input/components/Gif.module.css
  packages/ui/src/message-pane-input/components/ToolbarTop.jsx
  packages/ui/src/message-pane-input/components/modal/Modal.jsx
  packages/ui/src/message-pane-input/components/modal/assets/Ellipsis.svg
  packages/ui/src/message-pane-input/components/modal/assets/FileADD.svg
  packages/ui/src/message-pane-input/components/modal/assets/Laptop.svg
  packages/ui/src/message-pane-input/components/modal/assets/Thunderbolt.svg
  packages/ui/src/message-pane-input/components/modal/assets/bell-line.svg
  packages/ui/src/message-pane-input/components/modal/assets/folders-line.svg
  packages/ui/src/message-pane-input/components/modal/assets/google.svg
  packages/ui/src/message-pane-input/components/modal/assets/lightning.svg
  packages/ui/src/message-pane-input/components/modal/style.styled.js
Labels: accepted

#2647 Fixed the top margin of the rigth conner items
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
Labels: accepted

#2650 ZUR-196 My PR adds a feature
  packages/main/src/translations/translation-dictionary/pages/Pricing.js
Labels: Changes Requested

#2652 ZUR-169 Fix UI of add files modal on message input component
  .gitignore
  packages/ui/src/message-pane-input/components/SendFile.module.css
  packages/ui/src/message-pane-input/components/Toolbar.jsx
  packages/ui/src/message-pane-input/components/Toolbar2.jsx
  packages/ui/src/message-pane-input/components/ToolbarBottom.jsx
  packages/ui/src/message-pane-input/components/ToolbarTop.jsx
Labels: accepted

#2649 ZUR-178 Persist last view
  packages/main/src/auth/use-auth.js
  packages/main/src/pages/login/Login.jsx
  packages/main/src/pages/protected/workspace/Workspace.jsx
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
Labels: accepted

#2618 Fix/profilepic be fix
  packages/main/src/components/protected/topbar/components/EditProfile.jsx
Labels: Changes Requested

#2653 ZUR-98 My PR adds a search button and search icon to the global search.
  packages/main/src/components/protected/topbar/components/SearchBar.jsx
  packages/main/src/components/protected/topbar/components/TopBarSearchModal.jsx
  packages/main/src/components/protected/topbar/components/TopSearchBar.jsx
  packages/main/src/components/protected/topbar/styles/SearchBar.module.css
  packages/main/src/components/protected/topbar/styles/TopBarSearchModal.module.css
Labels: accepted

#2633 ZUR-127 Remove member in channel modal
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
  packages/ui/src/message-room-details-dialog/components/RemoveMemberModal.jsx
Labels: accepted

#2655 My PR Fixes ID-ZUR-123
  package.json
  packages/main/src/components/form/AuthInputBox.module.css
Labels: accepted

#2651 ZUR-186 Google login
  packages/main/src/components/google-auth/index.js
Labels: pending fix

#2654 Creating a ui for creating a new channel
  packages/main/src/components/protected/sidebar/components/Drop.jsx
  packages/main/src/components/protected/sidebar/components/DropRoom.jsx
  packages/main/src/components/protected/sidebar/components/ToggleSwitch.jsx
  packages/main/src/components/protected/sidebar/styles/Drop.module.css
Labels: Conflicts

#2504 Ticket ID ZCG_5: Remove the All DMs functionality
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/topbar/components/SidebarPreference.jsx
  packages/main/src/pages/protected/workspace/Workspace.jsx
Labels: accepted

#2661 Feat: TEA 117 and TEA124 Code the sidebar from slack for multiple workspaces and fetch data
  packages/main/src/components/protected/sidebar/components/Header.jsx
  packages/main/src/components/protected/topbar/components/TopNavbar.jsx
  packages/main/src/pages/protected/workspace/Workspace.jsx
  packages/main/src/pages/protected/workspace/Workspace.module.css
Labels: Changes Requested

#2662 feat: Search member functionality added to the channels
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
Labels: Changes Requested

#2664 FE-40: Translated the Subscribe section in 7 additional languages
  packages/main/src/components/subscribe-to-newsletter/NewsLetterSubscribtionThankYouModal.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/translations/translation-dictionary/pages/Subscribe.js
Labels: accepted

#2665 Feat: FE-41:Translate Zuri-Chat Footer component
  packages/main/src/components/footer/Footer.jsx
  packages/main/src/components/user-organisations-listing/UserOrganisationsListing.jsx
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx
  packages/main/src/pages/static/contact-us/components/ContactMain.jsx
  packages/main/src/pages/static/contact-us/components/FaqSelected.jsx
  packages/main/src/translations/translation-dictionary/components/Footer.js
Labels: accepted

#2667 Feat: FE-41/Translate Zuri-Chat Footer Component
  packages/main/src/components/footer/Footer.jsx
Labels: accepted

#2663 feat[FE-24]: added sidebar cache on local storage
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/sidebar/reducers/sidebar.reducer.js
  packages/main/src/utils/cache-sidebar.js
Labels: pending fix

#2678 FRO-27- feat: fix languages and region bug in preferences section of Zuri Chat
  packages/main/src/components/protected/topbar/components/AdvancedSettings.jsx
  packages/main/src/components/protected/topbar/components/LanguageAndRegion.jsx
  packages/main/src/components/protected/topbar/components/MessagesMedia.jsx
  packages/main/src/components/protected/topbar/components/NotificationPreference.jsx
  packages/main/src/components/protected/topbar/components/PreferenceMenu.jsx
  packages/main/src/translations/translation-dictionary/components/Preferences.js
  packages/main/src/translations/translation-dictionary/components/SideBar.js
  packages/main/src/translations/translation-dictionary/index.js
Labels: accepted

#2669 Feat:FE-44/translate zurichat contact us page.
  packages/main/src/pages/home/Home.jsx
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx
  packages/main/src/translations/translation-dictionary/pages/ContactUs.js
  packages/main/src/translations/translation-dictionary/pages/Home.js
Labels: accepted

#2668 Feat: FE-43 Translate Why Zuri Chat Page
  packages/main/src/pages/WhyZuriChat/Whyzurichat.js
  packages/main/src/translations/translation-dictionary/pages/whyzurichat.js
Labels: accepted

#2666 feat:FRO[77]leave channel functionality
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
  packages/ui/src/message-room-details-dialog/components/LeaveChannelModal.jsx
Labels: accepted

#2699 FE-58 Fix translation on sign out page
  packages/main/src/translations/translation-dictionary/pages/SignOut.js
Labels: accepted

#2671 feat[FE-46]: Translated Zurichat About page
  packages/main/src/pages/static/about/index.jsx
  packages/main/src/translations/translation-dictionary/pages/About.js
Labels: accepted

#2672 [FRO-82] Edit Topic on Channel Details Modal
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.styled.js
  packages/ui/src/message-room-details-dialog/components/EditTopicModal.jsx
Labels: accepted

#2677 FRO-8: Implement preview for file upload
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
Labels: accepted

#2679 fro-37-why-zuri-chat-features: implemented the why zuri chat page usi…
  packages/main/src/App.js
  packages/main/src/pages/static/whyzurichat/Body.jsx
  packages/main/src/pages/static/whyzurichat/FirstSection.jsx
  packages/main/src/pages/static/whyzurichat/SecondSection.jsx
  packages/main/src/pages/static/whyzurichat/ThirdSection.jsx
  packages/main/src/pages/static/whyzurichat/footer.jsx
  packages/main/src/pages/static/whyzurichat/images/align.svg
  packages/main/src/pages/static/whyzurichat/images/collaboration.svg
  packages/main/src/pages/static/whyzurichat/images/flexibility.svg
  packages/main/src/pages/static/whyzurichat/images/footerlogo.svg
  packages/main/src/pages/static/whyzurichat/images/globe.svg
  packages/main/src/pages/static/whyzurichat/images/organize.svg
  packages/main/src/pages/static/whyzurichat/images/productive.svg
  packages/main/src/pages/static/whyzurichat/images/transparency.svg
  packages/main/src/pages/static/whyzurichat/index.js
  packages/main/src/pages/static/whyzurichat/why.module.css
  packages/main/src/pages/static/whyzurichat/whyzurichat.css
Labels: accepted

#2675 [FE-45] Translate zurichat FAQs page
  packages/main/src/App.js
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.jsx
  packages/main/src/pages/static/contact-us/components/ContactFormContainer.module.css
  packages/main/src/pages/static/contact-us/faq/detailsArray.js
  packages/main/src/pages/static/whyzurichat/Body.jsx
  packages/main/src/pages/static/whyzurichat/FirstSection.jsx
  packages/main/src/pages/static/whyzurichat/SecondSection.jsx
  packages/main/src/pages/static/whyzurichat/ThirdSection.jsx
  packages/main/src/pages/static/whyzurichat/footer.jsx
  packages/main/src/pages/static/whyzurichat/index.js
  packages/main/src/translations/translation-dictionary/components/FAQ.js
  packages/main/src/translations/translation-dictionary/index.js
Labels: accepted

#2680 Feat/FRO-49 Implemented the zurichat downloads page
  packages/main/src/App.js
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/pages/downloads/Downloads.jsx
  packages/main/src/pages/downloads/downloads.module.css
  packages/main/src/pages/static/downloads/assets/brush.png
  packages/main/src/pages/static/downloads/assets/chat.png
  packages/main/src/pages/static/downloads/assets/copy.png
  packages/main/src/pages/static/downloads/assets/index.js
  packages/main/src/pages/static/downloads/assets/people.png
  packages/main/src/pages/static/downloads/assets/zuri.png
  packages/main/src/pages/static/downloads/components/Downloads.jsx
  packages/main/src/pages/static/downloads/components/downloads.module.css
  packages/main/src/pages/static/downloads/components/index.js
  packages/main/src/pages/static/downloads/index.jsx
Labels: accepted

#2681 fix:(FE-53) translate navbar zurichat
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/translations/translation-dictionary/components/NavBar.js
Labels: accepted

#2692 Feat/FRO-10:implenmented upload of files on zurichat
  package.json
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
  packages/ui/src/message-pane-input/components/ToolbarBottom.jsx
Labels: accepted

#2673 Fix: FE-47/translate landing page
  packages/main/src/translations/translation-dictionary/pages/Home.js
Labels: accepted

#2683 FE-48: Translate Zuri chat Login Page
  packages/main/src/pages/login/Login.jsx
  packages/main/src/translations/translation-dictionary/pages/Login.js
Labels: accepted

#2694 my PR closes the issue of translation of create workspace page, and cookie notification page
  packages/main/src/pages/protected/create-workspace/LaunchWorkspace.jsx
  packages/main/src/pages/protected/create-workspace/Step0.jsx
  packages/main/src/pages/protected/create-workspace/Step1.jsx
  packages/main/src/pages/protected/create-workspace/Step2.jsx
  packages/main/src/pages/protected/create-workspace/Step3.jsx
  packages/main/src/translations/translation-dictionary/pages/Cookies.js
  packages/main/src/translations/translation-dictionary/pages/Workspace.js
Labels: accepted

#2701 FIX: FE-61/Translate ZuriChat Plugins Page
  packages/main/src/pages/static/plugins/index.jsx
  packages/main/src/translations/translation-dictionary/pages/Plugins.js
Labels: accepted

#2709 Feat/scroll
  packages/main/src/components/protected/sidebar/components/EditWorkspaceModal.jsx
  packages/ui/src/message-board/MessageBoard.jsx
Labels: Changes Requested

#2712 Fix: FE-63/translate zurichat preferences page
  packages/main/src/translations/translation-dictionary/components/Preferences.js
Labels: accepted

#2689 FE-42 - Translate Zuri Chat Sign Up Page
  packages/main/src/pages/sign-up/SignUp.jsx
  packages/main/src/translations/translation-dictionary/pages/SignUp.js
Labels: accepted

#2704 feat:(FE-43): redesign the sidebar for the chats pages
  packages/main/src/components/protected/sidebar/components/Drop.jsx
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/sidebar/components/SingleRoom.jsx
  packages/main/src/components/protected/sidebar/styles/Drop.module.css
  packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
  packages/main/src/components/protected/topbar/styles/Topbar.module.css
  packages/main/src/pages/protected/workspace/Workspace.module.css
  packages/main/src/pages/protected/workspace/Workspace.style.js
Labels: pending fix, Changes Requested

#2682 Feat(FRO-76):Create a new thread through reply icon
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/sidebar/styles/Drop.module.css
  packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
  packages/ui/src/comment-board/CommentBoard.jsx
  packages/ui/src/comment-board/CommentBoard.styled.js
  packages/ui/src/message-board/MessageBoard.jsx
  packages/ui/src/message-board/MessageBoard.styled.js
  packages/ui/src/message-pane/MessagePane.jsx
  packages/ui/src/message-pane/components/hover-items/HoverItems.jsx
  packages/ui/src/message-pane/components/message-box/MessageBox.jsx
  packages/ui/src/message-pane/message-pane.module.css
  packages/ui/src/message-room-view-header/message-room-view-header.module.css
  packages/ui/src/utils/samples/sample-messages.js
Labels: accepted

#2710 corrected styling in profile section
  packages/main/src/components/protected/topbar/components/Profile.jsx
  packages/main/src/components/protected/topbar/styles/Profile.module.css
  packages/main/src/translations/translation-dictionary/components/Preferences.js
Labels: accepted

#2719 FRO-70: ZURI CHAT-Fix the admin settings home page and route properly.
  packages/main/src/App.js
  packages/main/src/components/admin-header/AdminHead.module.css
  packages/main/src/components/admin-header/AdminHeader.jsx
  packages/main/src/components/admin-header/assets/Mastercard.svg
  packages/main/src/components/admin-header/assets/american-express.svg
  packages/main/src/components/admin-header/assets/dinners-club.svg
  packages/main/src/components/admin-header/assets/discover.svg
  packages/main/src/components/admin-header/assets/jcb.svg
  packages/main/src/components/admin-header/assets/visa.svg
  packages/main/src/components/admin-header/utils/Api.jsx
  packages/main/src/components/admin-header/utils/Common.jsx
  packages/main/src/components/admin-header/utils/styles/PaymentMethod.module.css
  packages/main/src/components/admin-sidebar/AdminSidebar.jsx
  packages/main/src/components/admin-sidebar/AdminSidebar.module.css
  packages/main/src/components/admin-sidebar/assets/Mastercard.svg
  packages/main/src/components/admin-sidebar/assets/american-express.svg
  packages/main/src/components/admin-sidebar/assets/avatar.svg
  packages/main/src/components/admin-sidebar/assets/bouy.svg
  packages/main/src/components/admin-sidebar/assets/dinners-club.svg
  packages/main/src/components/admin-sidebar/assets/discover.svg
  packages/main/src/components/admin-sidebar/assets/grid.svg
  packages/main/src/components/admin-sidebar/assets/jcb.svg
  packages/main/src/components/admin-sidebar/assets/la_rocket.svg
  packages/main/src/components/admin-sidebar/assets/visa.svg
  packages/main/src/components/admin-sidebar/assets/zuriLogo.svg
  packages/main/src/components/admin-sidebar/utils/Api.jsx
  packages/main/src/components/admin-sidebar/utils/Common.jsx
  packages/main/src/components/admin-sidebar/utils/styles/PaymentMethod.module.css
  packages/main/src/components/protected/sidebar/components/Drop.jsx
  packages/main/src/pages/protected/admin-settings/AdminSettings.jsx
  packages/main/src/pages/protected/admin-settings/AdminSettings.module.css
  packages/main/src/pages/protected/settings-home/SettingsHome.jsx
  packages/main/src/pages/protected/settings-home/SettingsHome.module.css
  packages/main/src/pages/protected/settings-home/assets/Mastercard.svg
  packages/main/src/pages/protected/settings-home/assets/american-express.svg
  packages/main/src/pages/protected/settings-home/assets/cheveron-right.svg
  packages/main/src/pages/protected/settings-home/assets/dinners-club.svg
  packages/main/src/pages/protected/settings-home/assets/discover.svg
  packages/main/src/pages/protected/settings-home/assets/jcb.svg
  packages/main/src/pages/protected/settings-home/assets/visa.svg
  packages/main/src/pages/protected/settings-home/utils/Api.jsx
  packages/main/src/pages/protected/settings-home/utils/Common.jsx
  packages/main/src/pages/protected/settings-home/utils/styles/PaymentMethod.module.css
Labels: Changes Requested

#2720 fix(FRO-37): Ensure user avatar is displayed properly in the chat sec…
  packages/main/src/components/protected/topbar/components/EditProfile.jsx
  packages/main/src/components/protected/topbar/components/TopNavbar.jsx
Labels: accepted

#2721 Fix: Fix header on main chat room not aligned
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
  packages/main/src/pages/protected/workspace/Workspace.style.js
  packages/root-config/src/assets/plugin.importmap.json
  packages/ui/src/comment-board/CommentBoard.jsx
  packages/ui/src/comment-board/CommentBoard.styled.js
  packages/ui/src/message-board/MessageBoard.styled.js
  packages/ui/src/message-room-view-header/message-room-view-header.module.css
Labels: Changes Requested

#2725 Fixes Sidebar width and Spacing
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/sidebar/styles/Drop.module.css
  packages/main/src/pages/protected/workspace/Workspace.style.js
Labels: accepted

#2727 Fix/profile UI
  packages/main/src/components/protected/sidebar/components/Drop.jsx
  packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
  packages/main/src/components/protected/topbar/components/NotificationPreference.jsx
  packages/main/src/components/protected/topbar/components/Profile.jsx
  packages/main/src/components/protected/topbar/components/ProfileMore.jsx
  packages/main/src/components/protected/topbar/components/TopbarModal.jsx
  packages/main/src/components/protected/topbar/hooks/useClickOutside.jsx
  packages/main/src/components/protected/topbar/styles/Profile.module.css
  packages/main/src/components/protected/topbar/styles/Topbar.module.css
  packages/ui/src/message-room-view-header/message-room-view-header.module.css
Labels: accepted

#2676 Feat/Fe-27- Implelment video call using Agora
  example.env
  packages/main/package.json
  packages/main/src/components/media-chat/VideoChat.jsx
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/pages/protected/workspace/Workspace.jsx
  packages/main/src/pages/protected/workspace/Workspace.style.js
  yarn.lock
Labels: accepted

#2734 minor UI adjustments on zc_main plugin load section
  packages/main/src/pages/protected/workspace/Workspace.style.js
  packages/ui/src/message-board/MessageBoard.styled.js
Labels: accepted

#2735 fix: fixed profile ui issues
  packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
  packages/main/src/components/protected/topbar/components/NotificationPreference.jsx
  packages/main/src/components/protected/topbar/components/Profile.jsx
  packages/main/src/components/protected/topbar/components/ProfileMore.jsx
  packages/main/src/components/protected/topbar/components/TopbarModal.jsx
  packages/main/src/components/protected/topbar/hooks/useClickOutside.jsx
  packages/main/src/components/protected/topbar/styles/Profile.module.css
  packages/main/src/components/protected/topbar/styles/Topbar.module.css
Labels: accepted

#2736 Feat/FRO-49 Implemented the zurichat downloads page
  packages/main/src/pages/static/downloads/components/downloads.module.css
Labels: accepted

#2717 Feat(FRO-80): Description edit functionality
  packages/ui/src/message-pane-input/components/ToolbarBottom.jsx
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.styled.js
  packages/ui/src/message-room-details-dialog/components/EditDescriptionModal.jsx
Labels: accepted

#2723 Fix: included more languages from the language/region section
  packages/main/src/components/protected/sidebar/components/Drop.jsx
  packages/main/src/components/protected/topbar/components/LanguageAndRegion.jsx
  packages/main/src/translations/translation-dictionary/components/Preferences.js
Labels: accepted

#2698 Feat:FE-60/translate the zurichat reset pasword page,Feat:FE-67/translate zurichat privacy policy page
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/pages/static/contact-us/faq/es.js
  packages/main/src/pages/static/privacy-policy/components/Content.js
  packages/main/src/pages/static/privacy-policy/policyData.js
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/PrivacyPolicy.js
  packages/main/src/translations/translation-dictionary/pages/ResetPassword.js
Labels: accepted

#2733 Feat : FE-64/translate the zuri chat edit profile page / FE-58 Fix hebrew translation in signout page
  packages/main/src/components/protected/topbar/components/EditProfile.jsx
  packages/main/src/translations/translation-dictionary/components/EditProfile.js
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/SignOut.js
Labels: accepted

#2732 FIX: FE-66/translate zurichat profile page
  packages/main/src/components/protected/topbar/components/Profile.jsx
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/Profile.js
Labels: accepted

#2685 [FE-28] Implemented Live broadcast feature
  example.env
  packages/main/package.json
  packages/main/src/components/media-chat/LiveBroadcast.jsx
  packages/main/src/components/protected/sidebar/assets/icons/newlive.svg
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/pages/protected/workspace/Workspace.jsx
  yarn.lock
Labels: accepted

#2711 Archive and delete channel functionality
  package.json
  packages/ui/src/message-room-details-dialog/components/ArchiveChannel.jsx
  packages/ui/src/message-room-details-dialog/components/ChannelModal.jsx
  packages/ui/src/message-room-details-dialog/components/DeleteChannel.jsx
  packages/ui/src/message-room-details-dialog/components/archive-channel.module.css
  packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx
Labels: accepted

#2740 ZURI CHAT - My PR fixes Manage your Workspace page Link and route properly
  packages/main/src/App.js
  packages/main/src/components/admin-sidebar/AdminSidebar.jsx
  packages/main/src/components/calls/Calls.jsx
  packages/main/src/components/default-channel/DefaultChannel.jsx
  packages/main/src/components/display-email/DisplayEmail.jsx
  packages/main/src/components/display-name/DisplayName.jsx
  packages/main/src/components/display-pronoun/DisplayPronoun.jsx
  packages/main/src/components/file-retention/FileRetention.jsx
  packages/main/src/components/guidelines/Guidelines.jsx
  packages/main/src/components/join-channel/JoinChannel.jsx
  packages/main/src/components/join-workspace/JoinWorkspace.jsx
  packages/main/src/components/manage-members/ManageMembers.jsx
  packages/main/src/components/manage-members/Members.module.css
  packages/main/src/components/manage-members/assets/Mastercard.svg
  packages/main/src/components/manage-members/assets/american-express.svg
  packages/main/src/components/manage-members/assets/dinners-club.svg
  packages/main/src/components/manage-members/assets/discover.svg
  packages/main/src/components/manage-members/assets/jcb.svg
  packages/main/src/components/manage-members/assets/search.svg
  packages/main/src/components/manage-members/assets/visa.svg
  packages/main/src/components/manage-members/utils/Api.jsx
  packages/main/src/components/manage-members/utils/Common.jsx
  packages/main/src/components/manage-members/utils/styles/PaymentMethod.module.css
  packages/main/src/components/message-retention/MessageRetention.jsx
  packages/main/src/components/notify-user/NotifyUsers.jsx
  packages/main/src/components/options-popup/OptionsPopUp.jsx
  packages/main/src/components/options-popup/OptionsPopUp.module.css
  packages/main/src/components/table/Members.module.css
  packages/main/src/components/table/Table.jsx
  packages/main/src/components/table/assets/avatar.png
  packages/main/src/components/table/assets/search.svg
  packages/main/src/components/tool-tip-menu/OptionsPopUp.module.css
  packages/main/src/components/tool-tip-menu/ToolTipMenu.jsx
  packages/main/src/components/tool-tip-menu/assets/three-dots.svg
  packages/main/src/components/workspace-language/WorkspaceLanguage.jsx
  packages/main/src/pages/protected/manage-workspace/ManageWorkspace.css
  packages/main/src/pages/protected/manage-workspace/ManageWorkspace.jsx
  packages/main/src/pages/protected/manage-workspace/preference.module.css
  packages/main/src/pages/protected/manage-workspace/utils/Api.jsx
  packages/main/src/pages/protected/manage-workspace/utils/Common.jsx
  packages/main/src/pages/protected/preference-wrapper/Preference.module.css
  packages/main/src/pages/protected/preference-wrapper/PreferenceWrapper.jsx
  packages/main/src/pages/protected/settings-home/SettingsHome.jsx
Labels: Changes Requested

#2747 ZURI CHAT-Fix the about this workspace link and route properly
  packages/main/src/App.js
  packages/main/src/components/about-workspace-tabs/AboutWorkSpaceTabs.jsx
  packages/main/src/components/about-workspace-tabs/AboutWorkspaceTab.module.css
  packages/main/src/components/admin-owners-item/AdminOwnersItem.jsx
  packages/main/src/components/admin-owners-item/AdminOwnersItem.module.css
  packages/main/src/components/admin-owners-item/assets/avatar.svg
  packages/main/src/components/admin-owners/AdminOwners.jsx
  packages/main/src/components/admin-owners/AdminOwners.module.css
  packages/main/src/components/admin-sidebar/AdminSidebar.jsx
  packages/main/src/components/overview-workspace/OverviewWorkspace.jsx
  packages/main/src/components/overview-workspace/OverviewWorkspace.module.css
  packages/main/src/components/overview-workspace/assets/avatar.svg
  packages/main/src/components/retention-exports/Retention.module.css
  packages/main/src/components/retention-exports/RetentionAndExports.jsx
  packages/main/src/pages/protected/about-workspace/AboutWorkSpace.jsx
  packages/main/src/pages/protected/about-workspace/AboutWorkspace.module.css
  packages/main/src/pages/protected/about-workspace/utils/Api.jsx
Labels: accepted

#2726 Feat:TEA-226/converted uuids of Zuri Chat to shorter slugs
  packages/main/src-old/pages/admin/AboutWorkSpace.js
  packages/main/src-old/pages/createworkspace/components/CompanyName.js
  packages/main/src-old/pages/createworkspace/components/WorkspaceHome.js
  packages/main/src/components/protected/sidebar/components/PluginRoomAddUser.jsx
  packages/main/src/components/protected/sidebar/components/Room.jsx
  packages/main/src/components/protected/sidebar/components/RoomItem.jsx
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/sidebar/components/SingleRoom.jsx
  packages/main/src/components/protected/sidebar/components/invite-workflow/EmailInviteModal.jsx
  packages/main/src/components/protected/sidebar/utils/get-user-info.js
  packages/main/src/components/protected/topbar/components/Profile.jsx
  packages/main/src/components/protected/topbar/utils/common.js
  packages/main/src/components/user-organisations-listing/UserOrganisationsListing.jsx
  packages/main/src/pages/protected/create-workspace/LaunchWorkspace.jsx
  packages/main/src/pages/protected/create-workspace/Step3.jsx
  packages/main/src/pages/protected/workspace/Workspace.jsx
  packages/main/src/pages/protected/workspace/useParamHook.jsx
  packages/marketplace/src/marketplace/components/MarketPlaceContainer.js
  packages/marketplace/src/marketplace/marketplace.js
  packages/root-config/src/zuri-root-config.js
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
Labels: accepted

#2693 (FRO 36): Redesigning the contact us page
  packages/main/src/pages/static/contact-us/components/ContactMain.jsx
  packages/main/src/pages/static/contact-us/components/ContactMain.module.css
  packages/main/src/pages/static/contact-us/components/ContactMainBoard.jsx
  packages/main/src/pages/static/contact-us/components/ContactMainBoard.module.css
  packages/main/src/pages/static/contact-us/components/ContactSideBar.jsx
  packages/main/src/pages/static/contact-us/components/ContactSideBar.module.css
Labels: accepted

#2744 Feat:TEA-96- Add notification to the library and integrate it
  packages/main/package.json
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
  yarn.lock
Labels: accepted

#2748 ZURI CHAT- Send PATCH Requests to API from Admin Settings
  packages/main/src/components/change-email/ChangeEmail.jsx
  packages/main/src/components/save-password/SavePassword.jsx
  packages/main/src/components/use-form-hook/index.js
Labels: accepted

#2758 Fix/url room
  packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
  packages/main/src/components/protected/topbar/components/TopNavbar.jsx
  packages/main/src/components/protected/topbar/utils/common.js
  packages/main/src/pages/protected/workspace/Workspace.jsx
Labels: accepted

#2759 fix(FRO-83): removed engine restriction and node lock
  .npmrc
  package.json
Labels: accepted

#2760 chore: Add env support
  .env.example
  .gitignore
  example.env
  packages/main/src/components/media-chat/LiveBroadcast.jsx
  packages/main/src/components/media-chat/VideoChat.jsx
  packages/main/src/components/media-chat/VoiceCall/VoiceCall.jsx
  packages/utilities/environments/.env.development
  packages/utilities/environments/.env.example
  packages/utilities/package.json
  packages/utilities/src/constants.js
  packages/utilities/trash/root.component.js
  packages/utilities/trash/themecolors.js
  packages/utilities/webpack.config.js
  yarn.lock
Labels: accepted

#2745 fix(ZUR-7): fix and Improve search functionality
  packages/main/src/components/protected/topbar/components/BigModal.jsx
  packages/main/src/components/protected/topbar/components/SearchValueComponent.jsx
  packages/main/src/components/protected/topbar/components/TopBarSearchModal.jsx
  packages/main/src/components/protected/topbar/components/TopBarSearchModalUI.jsx
  packages/main/src/components/protected/topbar/components/TopNavbar.jsx
  packages/main/src/components/protected/topbar/styles/BigModal.module.css
  packages/main/src/components/protected/topbar/styles/SearchValueComponent.module.css
  packages/main/src/components/protected/topbar/styles/TopBarSearchModalUI.module.css
  packages/main/src/pages/protected/workspace/Workspace.jsx
  yarn.lock
Labels: accepted
