Repository zurichat/zc_main, pull requests merged in 2022-12, with the labels that each got.

#2769 Fix/profile UI bugs
  packages/main/src/components/protected/sidebar/components/ModalComponent.jsx
  packages/main/src/components/protected/topbar/components/EditProfile.jsx
  packages/main/src/components/protected/topbar/components/NotificationPreference.jsx
  packages/main/src/components/protected/topbar/components/ProfileModal.jsx
  packages/main/src/components/protected/topbar/components/TopNavbar.jsx
  packages/main/src/components/protected/topbar/styles/NotificationPreference.module.css
  packages/main/src/components/protected/topbar/styles/PreferenceMenu.module.css
  packages/main/src/components/protected/topbar/styles/ProfileModal.module.css
  packages/main/src/components/protected/topbar/styles/StyledEditProfile.styled.js
  packages/main/src/components/protected/topbar/styles/UserPreference.module.css
Labels: accepted

#2742 FE-59 Fix: translated zuri chat choose-workspace page
  packages/main/src/pages/protected/choose-workspace/ChooseWorkspace.jsx
  packages/main/src/pages/protected/create-workspace/Step1.jsx
  packages/main/src/translations/translation-dictionary/pages/Workspace.js
Labels: accepted

#2764 Added a notification library and integrated it
  packages/main/package.json
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
  packages/main/yarn.lock
Labels: accepted

#2768 fix: fixed bug in zc_main sending multiple request on page load to the same endpoint https://staging.api.zuri.chat/organizations/${orgId}/members/${user._id}
  packages/main/src/components/protected/topbar/components/TopNavbar.jsx
  packages/main/src/pages/protected/choose-workspace/ChooseWorkspace.jsx
Labels: accepted

#2778 enhancement (FEC-100): ditched all unnessary files and codes, redesig…
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
  packages/main/src/pages/static/contact-us/components/ContactMain.jsx
  packages/main/src/pages/static/contact-us/components/ContactMainBoard.jsx
  packages/main/src/pages/static/contact-us/components/ContactMainBoard.module.css
  packages/main/src/pages/static/contact-us/components/ContactSideBar.jsx
  packages/main/src/pages/static/contact-us/components/ContactSideBar.module.css
  packages/main/src/translations/translation-dictionary/components/NavBar.js
  yarn.lock
Labels: accepted

#2765 Fro 42 error page
  packages/main/src/App.js
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
  packages/main/src/pages/ErrorPage/TheFooter/TheFooter.jsx
  packages/main/src/pages/ErrorPage/TheFooter/TheFooter.module.css
  packages/main/src/pages/ErrorPage/assets/OOPS.svg
  packages/main/src/pages/ErrorPage/assets/Zuri Chat Logo.svg
  packages/main/src/pages/ErrorPage/assets/errorpic.svg
  packages/main/src/pages/ErrorPage/errorPage.jsx
  packages/main/src/pages/ErrorPage/errorPage.module.css
  packages/main/src/pages/index.js
Labels: accepted

#2751 Fix/video chat
  packages/main/src/components/media-chat/VideoChat.jsx
  packages/main/src/components/media-chat/VideoChat.module.css
  packages/main/src/pages/protected/workspace/Workspace.style.js
Labels: accepted

#2789 Made some UI changes
  packages/main/src/pages/static/contact-us/components/ContactMain.jsx
  packages/main/src/pages/static/contact-us/components/ContactMain.module.css
  packages/main/src/pages/static/contact-us/components/ContactMainBoard.jsx
  packages/main/src/pages/static/contact-us/components/ContactMainBoard.module.css
Labels: accepted

#2790 ZURI CHAT-Fix the Change Workspace Name link and route properly.
  packages/main/src/App.js
  packages/main/src/components/change-workspace-name/ChangeWorkspaceName.jsx
  packages/main/src/components/change-workspace-name/ChangeWorkspaceName.module.css
  packages/main/src/components/change-workspace-name/assets/default.svg
  packages/main/src/pages/protected/manage-workspace/ManageWorkspace.jsx
Labels: accepted

#2792 designed the landing page
  packages/main/src/pages/home/Home.jsx
  packages/main/src/pages/home/Home.module.css
  packages/main/src/translations/translation-dictionary/pages/Home.js
Labels: accepted

#2795 Fec 84 redesign zuri chat nav bar for mobile
  packages/main/src/components/footer/Footer.jsx
  packages/main/src/components/footer/Footer.module.css
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
Labels: accepted

#2801 feat(FE-110): Translated Downloads page on Zurichat
  packages/main/src/components/footer/Footer.jsx
  packages/main/src/components/protected/topbar/components/ProfileMore.jsx
  packages/main/src/pages/home/Home.jsx
  packages/main/src/pages/static/about/index.jsx
  packages/main/src/pages/static/downloads/components/Downloads.jsx
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/Download.js
  packages/main/src/translations/translation-dictionary/pages/ProfileMore.js
  packages/root-config/src/applications.js
Labels: accepted

#2802 fix the landing page errors
  packages/main/src/pages/home/Home.module.css
Labels: accepted

#2804 Fix: FE-115/translate-zurichat-edit-workspace-page
  packages/main/src/components/protected/sidebar/components/EditWorkspaceModal.jsx
  packages/main/src/components/top-navigation-bar/LanguageIcon.jsx
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
  packages/main/src/translations/translation-dictionary/components/EditWorkspace.js
  packages/main/src/translations/translation-dictionary/components/ModalComponent.js
  packages/main/src/translations/translation-dictionary/components/TopBarModal.js
  packages/main/src/translations/translation-dictionary/index.js
Labels: accepted

#2803 Feat/scroll
  packages/ui/src/message-board/MessageBoard.jsx
Labels: accepted

#2809 fix: Changed the Show Emoji Function to props
  packages/ui/src/message-board/MessageBoard.jsx
  packages/ui/src/message-room-view-header/message-room-view-header.module.css
Labels: accepted

#2806 Feat/ FE-116/ Translate ZuriChat Help Page
  packages/main/src/pages/static/help/index.jsx
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/Help.js
Labels: accepted

#2807 BE-74 Fix User Avatar Upload
  packages/main/src/components/protected/topbar/components/EditProfile.jsx
  packages/main/src/components/protected/topbar/components/TopNavbar.jsx
  packages/utilities/src/constants.js
Labels: accepted

#2814 chore (FEC-115): added link to zuri docs on topnavbar
  packages/main/src/components/top-navigation-bar/TopNavigationBar.jsx
Labels: accepted

#2816 feat: create channel bug fix and endpoint integrated
  packages/main/src/components/protected/sidebar/components/DropRoom.jsx
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
Labels: accepted

#2770 FEAT(FEC-79)
  packages/main/src/pages/static/privacy-policy/styles/content.module.css
Labels: accepted

#2805 Fec 98 implement zuri chat landing page
  packages/main/src/components/top-navigation-bar/TopNavigationBar.module.css
  packages/main/src/pages/static/legal/styles/HeaderStyle.module.css
Labels: accepted

#2817 ZURI CHAT - Fix the broken Customize link on the sidebar and the route properly.
  packages/main/src/App.js
  packages/main/src/components/add-prefix-modal/AddPrefixModal.jsx
  packages/main/src/components/add-prefix-modal/ChannelPrefixes.module.css
  packages/main/src/components/add-prefix-modal/assets/Mastercard.svg
  packages/main/src/components/add-prefix-modal/assets/american-express.svg
  packages/main/src/components/add-prefix-modal/assets/dinners-club.svg
  packages/main/src/components/add-prefix-modal/assets/discover.svg
  packages/main/src/components/add-prefix-modal/assets/jcb.svg
  packages/main/src/components/add-prefix-modal/assets/visa.svg
  packages/main/src/components/add-prefix-modal/utils/Api.jsx
  packages/main/src/components/add-prefix-modal/utils/Common.jsx
  packages/main/src/components/add-prefix-modal/utils/styles/PaymentMethod.module.css
  packages/main/src/components/channel-prefix/ChannelPrefix.jsx
  packages/main/src/components/channel-prefix/ChannelPrefixes.module.css
  packages/main/src/components/channel-prefixes/ChannelPrefixes.jsx
  packages/main/src/components/channel-prefixes/ChannelPrefixes.module.css
  packages/main/src/components/clear-time/ClearTIme.jsx
  packages/main/src/components/clear-time/ClearTime.module.css
  packages/main/src/components/content-wrapper/ContentWrapper.jsx
  packages/main/src/components/content-wrapper/ContentWrapper.module.css
  packages/main/src/components/emoji/Emoji.jsx
  packages/main/src/components/emoji/EmojiTab.module.css
  packages/main/src/components/emoji/utils/Api.jsx
  packages/main/src/components/logo-alert/LogoAlert.jsx
  packages/main/src/components/prefix-added/ChannelPrefixes.module.css
  packages/main/src/components/prefix-added/PrefixAdded.jsx
  packages/main/src/components/statuses/Statuses.jsx
  packages/main/src/components/statuses/Statuses.module.css
  packages/main/src/components/workspace-icon-change/WorkSpaceIconChange.jsx
  packages/main/src/components/workspace-icon-tab/WorkSpaceIconTab.jsx
  packages/main/src/components/workspace-icon-tab/assets/HNG-icon.svg
  packages/main/src/components/workspace-icon-tab/utils/Api.jsx
  packages/main/src/components/zuri-bot/ZuriBot.module.css
  packages/main/src/components/zuri-bot/Zuribot.jsx
  packages/main/src/components/zuri-bot/assets/Mastercard.svg
  packages/main/src/components/zuri-bot/assets/american-express.svg
  packages/main/src/components/zuri-bot/assets/dinners-club.svg
  packages/main/src/components/zuri-bot/assets/discover.svg
  packages/main/src/components/zuri-bot/assets/jcb.svg
  packages/main/src/components/zuri-bot/assets/visa.svg
  packages/main/src/components/zuri-bot/utils/Api.jsx
  packages/main/src/components/zuri-bot/utils/Common.jsx
  packages/main/src/components/zuri-bot/utils/styles/PaymentMethod.module.css
  packages/main/src/pages/protected/customize/Customize.jsx
Labels: accepted

#2821 Feature/create channel
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
  packages/ui/src/message-pane-input/components/ToolbarBottom.jsx
  packages/ui/src/message-pane/components/message-box/MessageBox.jsx
  packages/ui/src/message-pane/message-pane.module.css
  packages/ui/src/message-room-details-dialog/MessageRoomDetailsDialog.jsx
Labels: accepted

#2825 feat: verify current password and fix signout of all session leading …
  packages/main/src/components/save-password/SavePassword.jsx
  packages/main/src/components/save-password/SettingsTab.module.css
  packages/main/src/components/settings-tab/SettingsTab.jsx
Labels: accepted

#2829 Feat : FE-120/ ZuriChat Signout Translation fix/ Zurichat Pages and Components translation
  packages/main/src/components/about-workspace-tabs/AboutWorkSpaceTabs.jsx
  packages/main/src/components/account-profile-tabs/AccountProfileTabs.jsx
  packages/main/src/components/admin-owners/AdminOwners.jsx
  packages/main/src/components/admin-sidebar/AdminSidebar.jsx
  packages/main/src/components/calls/Calls.jsx
  packages/main/src/components/change-email/ChangeEmail.jsx
  packages/main/src/components/change-workspace-name/ChangeWorkspaceName.jsx
  packages/main/src/components/default-channel/DefaultChannel.jsx
  packages/main/src/components/display-email/DisplayEmail.jsx
  packages/main/src/components/display-name/DisplayName.jsx
  packages/main/src/components/display-pronoun/DisplayPronoun.jsx
  packages/main/src/components/email-verification-modal/EmailVerificationModal.jsx
  packages/main/src/components/file-retention/FileRetention.jsx
  packages/main/src/components/guidelines/Guidelines.jsx
  packages/main/src/components/join-channel/JoinChannel.jsx
  packages/main/src/components/join-workspace/JoinWorkspace.jsx
  packages/main/src/pages/sign-up/SignUp.jsx
  packages/main/src/pages/static/legal/component/Companies.js
  packages/main/src/pages/static/legal/components/Content.jsx
  packages/main/src/pages/static/plugins/components/EmailSubForm.jsx
  packages/main/src/pages/static/plugins/components/EmailSubModal.jsx
  packages/main/src/pages/static/plugins/components/ThankYouModal.jsx
  packages/main/src/pages/static/plugins/index.jsx
  packages/main/src/translations/translation-dictionary/index.js
  packages/main/src/translations/translation-dictionary/pages/Legal.js
  packages/main/src/translations/translation-dictionary/pages/MainComponents.js
Labels: accepted

#2824 Upgrade for PR #2807 #2823
  packages/main/src/components/protected/topbar/components/EditProfile.jsx
  packages/ui/src/comment-board/CommentBoard.jsx
  packages/ui/src/message-board/MessageBoard.jsx
Labels: accepted

#2835 ZURI CHAT-Fix the Deactivate Accounts link and route properly.
  packages/main/src/App.js
  packages/main/src/components/account-deactivated/AccDeactivated.jsx
  packages/main/src/components/account-deactivated/AccountDeactivated.module.css
  packages/main/src/components/account-deactivated/assets/zuri.svg
  packages/main/src/components/account-deactivation/AcctDeactivation.jsx
  packages/main/src/components/account-deactivation/AcctDeactivation.module.css
  packages/main/src/components/account-deactivation/assets/alertTriangle.svg
  packages/main/src/components/confirm-deactivation/ConfirmDeactivation.jsx
  packages/main/src/components/confirm-deactivation/ConfirmDeactivation.module.css
  packages/main/src/components/confirm-deactivation/utils/Common.jsx
  packages/main/src/components/settings-nav/SettingsNav.jsx
  packages/main/src/components/settings-nav/SettingsNav.module.css
  packages/main/src/components/settings-nav/assets/navImage.png
  packages/main/src/components/settings-nav/assets/zuri.svg
  packages/main/src/components/settings-tab/SettingsTab.jsx
Labels: accepted

#2836 Feat: make country code easy to use in edit profile
  packages/main/src/components/protected/topbar/components/EditProfile.jsx
  packages/main/src/components/protected/topbar/styles/StyledEditProfile.styled.js
  packages/main/src/components/protected/topbar/utils/country-code.js
Labels: Changes Requested

#2841 File preview
  packages/ui/src/message-pane-input/MessagePaneInput.jsx
  packages/ui/src/message-pane-input/components/ToolbarBottom.jsx
  packages/ui/src/message-pane/components/message-box/MessageBox.jsx
Labels: accepted

#2844 workspace loader for better UX
  packages/main/src/components/general-loading/WorkspaceLoading.jsx
  packages/main/src/components/general-loading/WorkspaceLoading.module.css
  packages/main/src/pages/protected/workspace/Workspace.jsx
  packages/main/src/pages/protected/workspace/Workspace.style.js
  packages/root-config/src/zuri-root-config.js
Labels: accepted

#2846 Fro/comment board threads
  packages/ui/src/comment-board/CommentBoard.jsx
  packages/ui/src/comment-board/CommentBoard.styled.js
  packages/ui/src/message-board/MessageBoard.jsx
Labels: accepted

#2847 Threads fix
  packages/main/src/pages/protected/invitations/Invitation.jsx
  packages/main/src/pages/protected/invitations/Invitation.module.css
  packages/ui/src/comment-board/CommentBoard.jsx
  packages/ui/src/comment-board/CommentBoard.styled.js
Labels: accepted

#2845 Workspace Settings: Back Button fails after navigation into 'workspace settings'
  packages/main/src/components/admin-sidebar/AdminSidebar.jsx
Labels: accepted

#2848 Threadsstyles fix
  packages/ui/src/comment-board/CommentBoard.jsx
  packages/ui/src/comment-board/CommentBoard.styled.js
Labels: accepted

#2839 Delete workspace
  packages/main/src/App.js
  packages/main/src/components/delete-workspace/assets/delete.svg
  packages/main/src/components/delete-workspace/deleteWorkspace.js
  packages/main/src/components/delete-workspace/deleteWorkspace.module.css
  packages/main/src/pages/protected/manage-workspace/ManageWorkspace.jsx
Labels: accepted

#2850 Fixed Modal Display and Sidebar Issues as Highlighted by David, HNG 9 Frontend PM for Zurichat
  packages/main/src/components/protected/sidebar/components/Header.jsx
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/main/src/components/protected/sidebar/styles/ModalComponentStyles.module.css
  packages/main/src/components/protected/sidebar/styles/Sidebar.module.css
Labels: accepted

#2852 Fix: Fix View Preference Modal not displaying in View Profile
  packages/main/src/components/protected/topbar/components/Profile.jsx
  packages/main/src/components/protected/topbar/components/ProfileMore.jsx
Labels: Changes Requested

#2856 Login page redesign
  packages/main/src/assets/zuri-chat-logo/logo-title.svg
  packages/main/src/components/admin-sidebar/AdminSidebar.jsx
  packages/main/src/components/form/AuthFormWrapper.module.css
  packages/main/src/components/form/AuthInputBox.module.css
  packages/main/src/pages/login/Login.jsx
  packages/main/src/pages/login/Login.module.css
Labels: Changes Requested

#2855 Fix: Undefined dom Element error fixed on page load
  packages/root-config/src/zuri-root-config.js
Labels: Changes Requested

#2859 feat: delete channel and archive channel functionality
  packages/main/src/components/protected/sidebar/components/Sidebar.jsx
  packages/ui/src/message-room-details-dialog/components/ArchiveChannel.jsx
  packages/ui/src/message-room-details-dialog/components/DeleteChannel.jsx
Labels: accepted

#2861 Fro file display
  packages/ui/src/comment-board/CommentBoard.styled.js
  packages/ui/src/message-pane/components/message-box/MessageBox.jsx
  packages/ui/src/message-pane/message-pane.module.css
Labels: accepted

#2864 Fix/UI fixes for display
  packages/main/src/components/language/Language.jsx
  packages/main/src/components/notification-tab/NotificationTab.jsx
  packages/main/src/components/preference-wrapper/SettingsTab.module.css
  packages/main/src/components/settings-tab/SettingsTab.jsx
  packages/main/src/pages/protected/settings-home/SettingsHome.jsx
  packages/main/src/translations/translation-dictionary/components/SettingsTab.js
Labels: accepted

#2851 My PR Fixes FRO-205 - change organization time zone
  package.json
  packages/main/src/components/language/Language.jsx
  packages/main/src/components/language/SettingsTab.module.css
  packages/main/src/components/settings-tab/SettingsTab.jsx
  packages/main/src/components/settings-tab/utils/Common.jsx
  packages/main/src/components/time-zone/SettingsTab.module.css
  packages/main/src/components/time-zone/TimeZone.jsx
  packages/main/src/translations/translation-dictionary/components/SettingsTab.js
  yarn.lock
Labels: accepted, Conflicts
